spring:
  application:
    name: nacos-seata-order-server
  datasource:
    url: jdbc:mysql://localhost:3306/seata-order?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
    type: com.alibaba.druid.pool.DruidDataSource

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 8080

ribbon:
  eager-load:
    enabled: true
    clients: nacos-seata-product-server

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000





