spring:
  cloud:
    gateway:
      routes:
        - id: niuh-timeBetween #id必须要唯一
          uri: lb://product-center
          predicates:
            #当前请求的时间必须在早上7点到 晚上11点 http://localhost:8888/selectProductInfoById/1
            #才会被转发
            #到http://product-center/selectProductInfoById/1
            - NiuhTimeBetween=上午7:00,下午11:00