spring:
  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://product-center
          predicates:
            #当前请求的时间必须在早上7点到 晚上11点 http://localhost:8888/selectProductInfoById/1
            #才会被转发
            #到http://product-center/selectProductInfoById/1
            - NiuhTimeBetween=上午7:00,下午11:00
          filters:
            #- AddRequestHeader=X-Request-Company,niuh
            #- AddRequestParameter=company, niuh
            #- AddResponseHeader=X-Request-Company, niuh
            #- PrefixPath=/product-api
            - TimeMonitor=enabled,true
